grails-app/services/ygor/EnrichmentService.groovy
src/groovy/de/hbznrw/ygor/export/DataMapper.groovy
src/groovy/de/hbznrw/ygor/export/Normalizer.groovy
src/groovy/de/hbznrw/ygor/export/structure/PackageHeader.groovy
src/groovy/de/hbznrw/ygor/export/structure/PackageHeaderNominalPlatform.groovy
src/groovy/de/hbznrw/ygor/export/structure/PackageStruct.groovy

See https://github.com/hbz/laser-ygor/issues/5#issuecomment-349958747 .

Modify nominalPlatform according to 5#issuecomment-349958747

---

application.properties
grails-app/controllers/ygor/EnrichmentController.groovy
grails-app/views/enrichment/_listDocuments.gsp
grails-app/views/index.gsp
src/groovy/de/hbznrw/ygor/bridges/EzbBridge.groovy
src/groovy/de/hbznrw/ygor/bridges/GbvBridge.groovy
src/groovy/de/hbznrw/ygor/bridges/HbzBridge.groovy
src/groovy/de/hbznrw/ygor/bridges/KbartBridge.groovy
src/groovy/de/hbznrw/ygor/bridges/ZdbBridge.groovy
src/groovy/de/hbznrw/ygor/connectors/DnbSruOiaDcConnector.groovy
src/groovy/de/hbznrw/ygor/connectors/DnbSruPicaConnector.groovy
src/groovy/de/hbznrw/ygor/connectors/EzbXmlConnector.groovy
src/groovy/de/hbznrw/ygor/connectors/GbvSruPicaConnector.groovy
src/groovy/de/hbznrw/ygor/connectors/KbartConnector.groovy
src/groovy/de/hbznrw/ygor/connectors/LobidJldConnector.groovy
src/groovy/de/hbznrw/ygor/connectors/ZdbdbSruPicaConnector.groovy
src/groovy/de/hbznrw/ygor/export/DataMapper.groovy
src/groovy/de/hbznrw/ygor/interfaces/AbstractConnector.groovy
src/groovy/de/hbznrw/ygor/interfaces/ConnectorInterface.groovy
src/groovy/de/hbznrw/ygor/processing/KbartProcessor.groovy
src/groovy/de/hbznrw/ygor/processing/MultipleProcessingThread.groovy
src/groovy/de/hbznrw/ygor/processing/Stash.groovy

We can review jointly if you like.

45 enrichment source order

---

grails-app/services/ygor/EnrichmentService.groovy
grails-app/services/ygor/GokbService.groovy
src/groovy/de/hbznrw/ygor/connectors/DnbSruPicaConnector.groovy
src/groovy/de/hbznrw/ygor/export/JsonTransformer.groovy

65 Switch to 'find' ES endpoint for already selected platforms

---

grails-app/views/enrichment/_howtostep1.gsp
grails-app/views/enrichment/_howtostep2.gsp
grails-app/views/enrichment/_listDocuments.gsp
grails-app/views/enrichment/config.gsp
src/groovy/de/hbznrw/ygor/export/DataMapper.groovy
src/groovy/de/hbznrw/ygor/export/Normalizer.groovy
src/groovy/de/hbznrw/ygor/export/Validator.groovy

Ebooks Changes 2

---

src/groovy/de/hbznrw/ygor/export/Normalizer.groovy
test/unit/de/hbznrw/ygor/export/NormalizerSpec.groovy
test/unit/de/hbznrw/ygor/export/ValidatorSpec.groovy

The tests in the project failed for some parameter issues. I tried to fix them and repaired the tested Class (Normalizer.groovy) to validate the according test.

Fixed Tests and repaired Normalizer.groovy

---

grails-app/controllers/ygor/EnrichmentController.groovy
src/groovy/de/hbznrw/ygor/export/Normalizer.groovy

* Fix the handling of another date format
* Change UTF-8 detection to accept null value, in concordance with open issue https://github.com/albfernandez/juniversalchardet/issues/23

Add new date normalizer case, fix encoding detection

---

src/groovy/de/hbznrw/ygor/validators/Validator.groovy

The other parts of this issue were solved with the changes comprised in #200.

Add EZB ID validation (#171)

---

grails-app/domain/ygor/Enrichment.groovy
grails-app/services/ygor/EnrichmentService.groovy
grails-app/views/enrichment/_listDocuments.gsp
src/groovy/de/hbznrw/ygor/export/GokbExporter.groovy
src/groovy/de/hbznrw/ygor/export/structure/Package.groovy
src/groovy/de/hbznrw/ygor/export/structure/PackageHeader.groovy
src/groovy/de/hbznrw/ygor/export/structure/PackageHeaderNominalPlatform.groovy
src/groovy/de/hbznrw/ygor/export/structure/PackageHeaderSource.groovy
src/groovy/de/hbznrw/ygor/export/structure/PackageStruct.groovy
src/groovy/de/hbznrw/ygor/export/structure/TippPlatform.groovy

- refactors code concerning package header
- handles package platform and package provider (that were set in the UI) over to the data export

203 fix missing provider and platform

---

src/groovy/de/hbznrw/ygor/validators/Validator.groovy

Allow date format YYYY-MM (fixes #202)

---

src/groovy/de/hbznrw/ygor/readers/KbartReader.groovy

@VolkerHBZ Please have a short look ;-) I'm going to merge anyway.

Fix BOM deletion (context of #219)

---

grails-app/domain/ygor/Record.groovy
grails-app/domain/ygor/field/MappingsContainer.groovy
src/groovy/de/hbznrw/ygor/export/GokbExporter.groovy
src/java/resources/YgorFieldKeyMapping.json

- Change order of enrichment
- Set coverage Issues and Numbers to String 
- Reset FieldKeyMapping to old values

Coverage fixes and enrichment order 0.89

---

grails-app/domain/ygor/Record.groovy
src/java/resources/YgorFieldKeyMapping.json

This PR is more for the purpose of letting you know. Hopefully not really for code corrections :-)

Allow publicationType "other" (openlibraryenvironment/gokb#277)

---

grails-app/controllers/ygor/EnrichmentController.groovy
grails-app/controllers/ygor/StatisticController.groovy
grails-app/domain/ygor/Enrichment.groovy
grails-app/services/ygor/AutoUpdateService.groovy
grails-app/services/ygor/EnrichmentService.groovy
grails-app/services/ygor/GokbService.groovy
grails-app/views/enrichment/_listDocuments.gsp
grails-app/views/statistic/show.gsp
src/groovy/de/hbznrw/ygor/processing/MultipleProcessingThread.groovy
src/groovy/de/hbznrw/ygor/readers/KbartReader.groovy

299 restructure enrichment

---

src/java/resources/YgorFieldKeyMapping.json

writing title properties in the title node of a tipp.

additional data fields

---

src/groovy/de/hbznrw/ygor/export/GokbExporter.groovy

Always keep titleId with provider namespace (also if it equals another ID)

---

grails-app/controllers/ygor/EnrichmentController.groovy
grails-app/domain/ygor/Enrichment.groovy
grails-app/services/ygor/AutoUpdateService.groovy
grails-app/services/ygor/EnrichmentService.groovy
src/groovy/de/hbznrw/ygor/processing/CompleteProcessingThread.groovy

Add new param 'ignoreLastChanged' to process complete enrichment (ERMS-3202)

---

src/groovy/de/hbznrw/ygor/export/GokbExporter.groovy
src/groovy/de/hbznrw/ygor/normalizers/EditionNormalizer.groovy
src/groovy/de/hbznrw/ygor/tools/JsonToolkit.groovy
src/java/resources/YgorFieldKeyMapping.json

... and fix GOKbIT-63 on the way.

ERMS-3184 little fixes in gokb output config ... 

---

grails-app/assets/stylesheets/ygor.css
grails-app/controllers/ygor/EnrichmentController.groovy
grails-app/domain/ygor/Enrichment.groovy
grails-app/domain/ygor/field/MultiField.groovy
grails-app/i18n/messages.properties
grails-app/i18n/messages_de.properties
grails-app/services/ygor/EnrichmentService.groovy
grails-app/services/ygor/GokbService.groovy
grails-app/views/enrichment/_listDocuments.gsp
src/groovy/de/hbznrw/ygor/export/GokbExporter.groovy

@Moetez16 @VolkerHBZ With this PR, packages are selectable being suggested like platforms and providers. New package names can still be entered in the select box.
The GOKb package id is being sent to the GOKb crossRef endpoint as `gokbId` in the package header.

3306 suggest package

---

src/java/resources/YgorFieldKeyMapping.json

@Moetez16 ddc is added to title, tipp.title and tipp.

Add ddc to YgorFieldKeyMapping (ERMS-3361)

---

grails-app/controllers/ygor/EnrichmentController.groovy
grails-app/domain/ygor/Enrichment.groovy
grails-app/services/ygor/AutoUpdateService.groovy
grails-app/services/ygor/EnrichmentService.groovy
grails-app/services/ygor/integrators/EzbIntegrationService.groovy
grails-app/services/ygor/integrators/ZdbIntegrationService.groovy
grails-app/views/enrichment/process.gsp
src/groovy/de/hbznrw/ygor/processing/CompleteProcessingThread.groovy
src/groovy/de/hbznrw/ygor/processing/MultipleProcessingThread.groovy
src/groovy/de/hbznrw/ygor/processing/YgorFeedback.groovy
src/groovy/de/hbznrw/ygor/readers/KbartFromUrlReader.groovy

Can be merged now in general.
Please check if the implementation covers the needs of GOKb and please name details in case they are missing.

95 ygor feedback

---

grails-app/controllers/ygor/EnrichmentController.groovy
grails-app/views/enrichment/_listDocuments.gsp
src/groovy/de/hbznrw/ygor/export/GokbExporter.groovy
src/groovy/de/hbznrw/ygor/normalizers/CommonNormalizer.groovy

Picks from gokb import

---

src/groovy/de/hbznrw/ygor/normalizers/AmountNormalizer.groovy

@Moetez16 Ein kleiner Nachschlag. Ist bereits auf DEV deployt, direkt vom Feature-Branch.

3639 amount format

---

grails-app/controllers/ygor/StatisticController.groovy

Allow processing results to be filtered by searching in the data tables view.

4038 reenable search results js

---

src/groovy/de/hbznrw/ygor/readers/KbartReader.groovy

@Moetez16 not sure why this did run locally without errors, but not on the server. It is working now, I have deployed directly from the fix-Branch on QA.
Please check and ping me after review, so I can deploy everything on PROD.

Fix validation tag lib exception
